// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7hWW4Xr3kXCqUHEZain1qxpMzn0X1zc',
    appId: '1:560526628443:web:083960e75ac00e42ab917e',
    messagingSenderId: '560526628443',
    projectId: 'medhat-wedding',
    authDomain: 'medhat-wedding.firebaseapp.com',
    storageBucket: 'medhat-wedding.firebasestorage.app',
    measurementId: 'G-4EV6E53NVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvikuLs8vXFXxnSEn2mPkjaq1eP6EGY6w',
    appId: '1:560526628443:android:4dee05d42ed73705ab917e',
    messagingSenderId: '560526628443',
    projectId: 'medhat-wedding',
    storageBucket: 'medhat-wedding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsdmkICz0FnWiMpcmJhsmKY0PD6YIRyEg',
    appId: '1:560526628443:ios:6a66a6dfcf277f99ab917e',
    messagingSenderId: '560526628443',
    projectId: 'medhat-wedding',
    storageBucket: 'medhat-wedding.firebasestorage.app',
    iosBundleId: 'com.example.medhatWedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsdmkICz0FnWiMpcmJhsmKY0PD6YIRyEg',
    appId: '1:560526628443:ios:6a66a6dfcf277f99ab917e',
    messagingSenderId: '560526628443',
    projectId: 'medhat-wedding',
    storageBucket: 'medhat-wedding.firebasestorage.app',
    iosBundleId: 'com.example.medhatWedding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV7hWW4Xr3kXCqUHEZain1qxpMzn0X1zc',
    appId: '1:560526628443:web:3c8507948c1e0ab0ab917e',
    messagingSenderId: '560526628443',
    projectId: 'medhat-wedding',
    authDomain: 'medhat-wedding.firebaseapp.com',
    storageBucket: 'medhat-wedding.firebasestorage.app',
    measurementId: 'G-F7J10FG3JS',
  );
}
