import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'package:wedding_invitation/firebase_options.dart';

import 'core/localization/app_language.dart';
import 'core/localization/locale_cubit.dart';
import 'core/theme/app_theme.dart';
import 'features/music/cubit/music_cubit.dart';
import 'features/music/presentation/music_toggle_button.dart';
import 'presentation/pages/splash_screen.dart';
import 'presentation/pages/wedding_home_page.dart';

// Generated by `flutterfire configure`. Run that command in the project
// root to create this file for your own Firebase project, then uncomment
// the import + usage below.
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Enables Arabic relative-time strings ("منذ 5 دقائق") in the guestbook.
  timeago.setLocaleMessages('ar', timeago.ArMessages());

  await Firebase.initializeApp(
     options: DefaultFirebaseOptions.currentPlatform,
    
  );

  runApp(
    MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => LocaleCubit()),
        BlocProvider(create: (_) => MusicCubit()),
      ],
      child: const WeddingInvitationApp(),
    ),
  );
}

class WeddingInvitationApp extends StatelessWidget {
  const WeddingInvitationApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<LocaleCubit, AppLanguage>(
      builder: (context, language) {
        return MaterialApp(
          title: 'Medhat & Nesma — Wedding Invitation',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.theme,
          locale: language.locale,
          supportedLocales: const [Locale('ar'), Locale('en')],
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          // `flutter_localizations` automatically wraps the app in a
          // Directionality that matches the resolved locale, so Arabic
          // (the default) renders fully right-to-left with zero extra
          // widgets needed anywhere else in the tree.
          home: const RootScreen(),
        );
      },
    );
  }
}

/// Hosts the splash/welcome screen and cross-fades into the main
/// invitation once it finishes (or the user taps "Skip"). Also owns the
/// "first tap anywhere unlocks audio" gesture listener and the always-on
/// floating music toggle button, so both work identically whether the
/// guest is still on the splash screen or already on the main page.
class RootScreen extends StatefulWidget {
  const RootScreen({super.key});

  @override
  State<RootScreen> createState() => _RootScreenState();
}

class _RootScreenState extends State<RootScreen> {
  bool _showSplash = true;

  void _finishSplash() {
    if (!mounted) return;
    setState(() => _showSplash = false);
  }

  @override
  Widget build(BuildContext context) {
    return Listener(
      // Browsers block audio-with-sound until the page gets a genuine
      // user gesture. This fires on the very first tap/click ANYWHERE on
      // the page (including the Skip button, a form field, etc.) and
      // asks MusicCubit to start playback if it hasn't already.
      behavior: HitTestBehavior.translucent,
      onPointerDown: (_) => context.read<MusicCubit>().unlockWithUserGesture(),
      child: Stack(
        children: [
          AnimatedSwitcher(
            duration: const Duration(milliseconds: 700),
            switchInCurve: Curves.easeOut,
            switchOutCurve: Curves.easeIn,
            child: _showSplash
                ? SplashScreen(key: const ValueKey('splash'), onFinished: _finishSplash)
                : const WeddingHomePage(key: ValueKey('home')),
          ),
          const Positioned(
            bottom: 20,
            right: 20,
            child: SafeArea(child: MusicToggleButton()),
          ),
        ],
      ),
    );
  }
}
