import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'package:wedding_invitation/firebase_options.dart';
import 'core/localization/app_language.dart';
import 'core/localization/locale_cubit.dart';
import 'core/theme/app_theme.dart';
import 'presentation/pages/splash_screen.dart';
import 'presentation/pages/wedding_home_page.dart';

// Generated by `flutterfire configure`. Run that command in the project
// root to create this file for your own Firebase project, then uncomment
// the import + usage below.
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Enables Arabic relative-time strings ("منذ 5 دقائق") in the guestbook.
  timeago.setLocaleMessages('ar', timeago.ArMessages());

  await Firebase.initializeApp(
     options: DefaultFirebaseOptions.currentPlatform,
   
  );

  runApp(
    BlocProvider(
      create: (_) => LocaleCubit(),
      child: const WeddingInvitationApp(),
    ),
  );
}

class WeddingInvitationApp extends StatelessWidget {
  const WeddingInvitationApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<LocaleCubit, AppLanguage>(
      builder: (context, language) {
        return MaterialApp(
          title: 'Medhat & Nesma — Wedding Invitation',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.theme,
          locale: language.locale,
          supportedLocales: const [Locale('ar'), Locale('en')],
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          // `flutter_localizations` automatically wraps the app in a
          // Directionality that matches the resolved locale, so Arabic
          // (the default) renders fully right-to-left with zero extra
          // widgets needed anywhere else in the tree.
          home: const RootScreen(),
        );
      },
    );
  }
}

/// Hosts the splash/welcome screen and cross-fades into the main
/// invitation once it finishes (or the user taps "Skip").
class RootScreen extends StatefulWidget {
  const RootScreen({super.key});

  @override
  State<RootScreen> createState() => _RootScreenState();
}

class _RootScreenState extends State<RootScreen> {
  bool _showSplash = true;

  void _finishSplash() {
    if (!mounted) return;
    setState(() => _showSplash = false);
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedSwitcher(
      duration: const Duration(milliseconds: 700),
      switchInCurve: Curves.easeOut,
      switchOutCurve: Curves.easeIn,
      child: _showSplash
          ? SplashScreen(key: const ValueKey('splash'), onFinished: _finishSplash)
          : const WeddingHomePage(key: ValueKey('home')),
    );
  }
}
