import 'dart:html' as html;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'package:wedding_invitation/firebase_options.dart';

import 'core/localization/app_language.dart';
import 'core/localization/locale_cubit.dart';
import 'core/theme/app_theme.dart';
import 'features/music/cubit/music_cubit.dart';
import 'features/music/presentation/music_toggle_button.dart';
import 'presentation/pages/splash_screen.dart';
import 'presentation/pages/wedding_home_page.dart';

// Generated by `flutterfire configure`. Run that command in the project
// root to create this file for your own Firebase project, then uncomment
// the import + usage below.
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Enables Arabic relative-time strings ("منذ 5 دقائق") in the guestbook.
  timeago.setLocaleMessages('ar', timeago.ArMessages());

  await Firebase.initializeApp(
     options: DefaultFirebaseOptions.currentPlatform,
    
  );

  final musicCubit = MusicCubit();

  // Web-only, and deliberately registered as a *raw DOM* listener rather
  // than a Flutter `Listener`/`GestureDetector`. On mobile browsers
  // (iOS Safari especially) Flutter's own pointer-event pipeline can add
  // just enough indirection that the browser no longer treats the
  // resulting call as "inside a trusted user gesture," so autoplay stays
  // blocked even though the exact same code works fine on desktop mouse
  // clicks. Listening directly on `document` for the browser's native
  // `click`/`touchend` events avoids that gap entirely. This complements
  // (rather than replaces) the Flutter-level `Listener` in [RootScreen]
  // below, so playback unlocks reliably on both desktop and mobile.
  html.document.addEventListener('click', (_) => musicCubit.unlockWithUserGesture());
  html.document.addEventListener('touchend', (_) => musicCubit.unlockWithUserGesture());

  runApp(
    MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => LocaleCubit()),
        BlocProvider.value(value: musicCubit),
      ],
      child: const WeddingInvitationApp(),
    ),
  );
}

class WeddingInvitationApp extends StatelessWidget {
  const WeddingInvitationApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<LocaleCubit, AppLanguage>(
      builder: (context, language) {
        return MaterialApp(
          title: 'Medhat & Nesma — Wedding Invitation',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.theme,
          locale: language.locale,
          supportedLocales: const [Locale('ar'), Locale('en')],
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          // `flutter_localizations` automatically wraps the app in a
          // Directionality that matches the resolved locale, so Arabic
          // (the default) renders fully right-to-left with zero extra
          // widgets needed anywhere else in the tree.
          home: const RootScreen(),
        );
      },
    );
  }
}

/// Hosts the splash/welcome screen and cross-fades into the main
/// invitation once it finishes (or the user taps "Skip"). Also owns a
/// Flutter-level "first tap anywhere unlocks audio" gesture listener
/// (complementing the raw DOM listener registered in `main()`) and the
/// always-on floating music toggle button.
class RootScreen extends StatefulWidget {
  const RootScreen({super.key});

  @override
  State<RootScreen> createState() => _RootScreenState();
}

class _RootScreenState extends State<RootScreen> {
  bool _showSplash = true;

  void _finishSplash() {
    if (!mounted) return;
    setState(() => _showSplash = false);
  }

  @override
  Widget build(BuildContext context) {
    return Listener(
      behavior: HitTestBehavior.translucent,
      // `onPointerUp` (closer to a browser "click"/"touchend") rather
      // than `onPointerDown` — mobile Safari in particular is fussy
      // about which gesture phase counts toward its autoplay allowance.
      onPointerUp: (_) => context.read<MusicCubit>().unlockWithUserGesture(),
      child: Stack(
        children: [
          AnimatedSwitcher(
            duration: const Duration(milliseconds: 700),
            switchInCurve: Curves.easeOut,
            switchOutCurve: Curves.easeIn,
            child: _showSplash
                ? SplashScreen(key: const ValueKey('splash'), onFinished: _finishSplash)
                : const WeddingHomePage(key: ValueKey('home')),
          ),
          const Positioned(
            bottom: 20,
            right: 20,
            child: SafeArea(child: MusicToggleButton()),
          ),
        ],
      ),
    );
  }
}
